# inherit_gem:
#   rubocop-rails:
#     - config/rails.yml

require: rubocop-rails

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: normal
