google:
  service: GCS
  project: instagram-images-261422
  credentials: <%= ENV['GOOGLE_APPLICATION_CREDENTIALS'].as_json %>
  bucket: example_pics

google_dev:
  service: GCS
  project: instagram-images-261422
  credentials: <%= Rails.root.join("config/secrets/example-pic.json") %>
  bucket: example_pics
